/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package org.test.with.groovy;

import javax.script.*;

public class App {

    public static void main(String[] args) {
        ScriptEngineManager factory = new ScriptEngineManager();
        ScriptEngine engine = factory.getEngineByName("groovy");

        String fact = "vr.r(1,3287)==12345 || vr.r(1,3287)==3469";
        PmClient pmClient = new PmClient();
        VariableReader vr = new VariableReader(pmClient, 182);

        ScriptContext context = new SimpleScriptContext();
        context.setAttribute("vr", vr, ScriptContext.ENGINE_SCOPE);

        engine.setContext(context);

        try {
            Object result = engine.eval(fact);
            assert result instanceof Boolean;
            assert (Boolean) result;
        } catch (ScriptException e) {
            throw new RuntimeException(e);
        }
    }
}
